In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import numpy as np


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/iris.csv')

In [ ]:
df

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width      Class
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
X = df.iloc[:,0:4].values


In [ ]:
Y = df.iloc[:,4].values

In [ ]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder= LabelEncoder()
x_scale=labelencoder.fit_transform(Y)

In [ ]:
x_scale

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
Y = pd.get_dummies(x_scale).values


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
print(X_train,X_test,Y_train,Y_test)

[[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]
 [5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.

In [ ]:
# from keras.models import Sequential
# from keras.layers import Dense

In [ ]:
model = keras.Sequential([
                          keras.layers.Dense(10, input_shape=(4,), activation='relu'),
                          keras.layers.Dense(10,activation='relu'),
                          keras.layers.Dense(3, activation='sigmoid'),
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 49s 3ms/step - loss: 1.9977 - accuracy: 0.3667
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.7706 - accuracy: 0.5833
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.5651 - accuracy: 0.6250
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.3854 - accuracy: 0.6333
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.2253 - accuracy: 0.6333
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0926 - accuracy: 0.6000
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9923 - accuracy: 0.4417
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9222 - accuracy: 0.4167
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8618 - accuracy: 0.5583
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8260 - accuracy: 0.6500
Epoch 11/100
4/4 [==========

In [ ]:


# model = tf.keras.Sequential([
#     tf.keras.layers.Dense(30, activation='relu',input_shape=(10,)),
#     tf.keras.layers.Dense(30, activation='relu'),
#     tf.keras.layers.Dense(3, activation='sigmoid')
#   ])
# model

In [ ]:
# model.compile(optimizer='sgd',
#               loss='sparce_categorical_crossentropy',
#               metrics=['accuracy'])

In [ ]:
# hist = model.fit(X_train, Y_train,
#                  batch_size=30, epochs=100,
#                  validation_data=(X_test, Y_test),
#                  )
                

In [ ]:
model.evaluate(X_test,Y_test)

1/1 [==============================] - 0s 128ms/step - loss: 0.3635 - accuracy: 0.8667


[0.3635168969631195, 0.8666666746139526]

In [ ]:
pred=model.predict(X_test)
pred

array([[0.22038254, 0.9017719 , 0.96282166],
       [0.3026483 , 0.8755044 , 0.9223871 ],
       [0.99464417, 0.44004565, 0.0202893 ],
       [0.17495227, 0.9195552 , 0.9862702 ],
       [0.98000956, 0.51577556, 0.05654371],
       [0.2276085 , 0.9279225 , 0.97143805],
       [0.98411334, 0.48258346, 0.04747725],
       [0.3568375 , 0.92636824, 0.90855473],
       [0.2902948 , 0.9127261 , 0.9425316 ],
       [0.39763486, 0.9110156 , 0.8591505 ],
       [0.23670232, 0.8978653 , 0.97097456],
       [0.4131325 , 0.929835  , 0.86666656],
       [0.35833716, 0.9111575 , 0.9124379 ],
       [0.30816573, 0.9110149 , 0.9292637 ],
       [0.35725364, 0.91514075, 0.9098413 ],
       [0.98881483, 0.4538953 , 0.03528342],
       [0.36539122, 0.9142759 , 0.8968558 ],
       [0.36839584, 0.8973944 , 0.8968121 ],
       [0.9598664 , 0.5599855 , 0.09525213],
       [0.9902225 , 0.4665166 , 0.03360194],
       [0.28078163, 0.90371907, 0.9418502 ],
       [0.41295624, 0.91775024, 0.86659676],
       [0.

In [ ]:
pred[12]

array([0.35833716, 0.9111575 , 0.9124379 ], dtype=float32)

In [ ]:
rounded = [round(x[0]) for x in pred]
print(rounded[12])

0
